apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 80
  selector:
    app: angular-frontend
  type: ClusterIP